version: "3.5"
services:
    app:
      build:
        context: .
        target: image_dev
      volumes:
          - ../project:/var/www/project
          - ./php/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
          - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      working_dir: /var/www/project
      environment:
        - PHP_IDE_CONFIG=serverName=app-local

    webserver:
      image: nginx:alpine
      volumes:
        - ../project:/var/www/project
        - ./nginx/default-local.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"
